HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INC_SUBDIR           = pointlike

HD_INSTALL_HEADERS      = Alignment.h \
			  AlignProc.h \
			  CalData.h \
			  ConfidenceLevel.h \
			  Data.h \
			  Draw.h \
			  HealpixDiffuseFunc.h \
			  LeastSquaresFitter.h \
			  ParamOptimization.h \
			  PointSourceLikelihood.h \
			  PowerLawFilter.h \
			  PsfFunction.h \
			  RotationInfo.h \
			  SimpleLikelihood.h \
			  SimpleTSmap.h \
			  SourceFinder.h \
			  SourceList.h

include ${HD_STD_MAKEFILE}
