HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INC_SUBDIR           = latResponse

HD_INSTALL_HEADERS      = Aeff.h Bilinear.h EdispInterpolator.h Edisp3.h FitsTable.h PsfBase.h IrfLoader.h ParTables.h Psf3.h

include ${HD_STD_MAKEFILE}
