HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INC_SUBDIR           = skymaps

HD_INSTALL_HEADERS      = Background.h \
			  BandBackground.h \
			  Band.h \
			  BinnedPhotonData.h \
			  ComplexSkySpectrum.h \
			  CompositeSkyFunction.h \
			  CompositeSkySpectrum.h \
			  Convolution.h \
			  DiffuseFunction.h \
			  EffectiveArea.h \
			  Exposure.h \
			  ExposureWeighter.h \
			  GtiBase.h \
			  Gti.h \
			  HealpixDiffuseFunc.h \
			  IParams.h \
			  IsotropicConstant.h \
			  IsotropicPowerLaw.h \
			  IsotropicSpectrum.h \
			  LivetimeCube.h \
			  PhotonBinner.h \
			  PhotonMap.h \
			  PsfFunction.h \
			  PsfSkyFunction.h \
			  PsfSkySpectrum.h \
			  PySkyFunction.h \
			  PySkySpectrum.h \
			  PythonPsf.h \
			  PythonUtilities.h \
			  SkyImage.h \
			  SkyImageSpectrum.h \
			  SkyIntegrator.h \
			  SkySpectrum.h \
			  SmoothedSkySpectrum.h \
			  SpectralFunction.h \
			  WeightedSkyDir.h 

include ${HD_STD_MAKEFILE}