HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_SUBDIRS              = skymaps src python data

HD_INSTALL_PYTHON_LIBS = skymaps.py

HD_TEST_SUBDIRS         = src/test

include ${HD_STD_MAKEFILE}
