HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INC_SUBDIR           = healpix

HD_INSTALL_HEADERS      = alm_filter_tools.h \
			  AlmOp.h \
                          CosineBinner.h \
                          HeallpixMap.h \
                          HealpixArray.h \
                          HealpixArrayIO.h \
                          HealPixel.h \
                          Healpix.h \
                          HealpixMap.h \
                          Map.h \
			  HealpixRegion.h

#HD_SUBDIRS              = base

include ${HD_STD_MAKEFILE}
