HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INC_SUBDIR           = irfUtil

HD_INSTALL_HEADERS      = dgaus8.h HdCaldb.h RootTable.h Util.h IrfHdus.h EventTypeMapper.h

include ${HD_STD_MAKEFILE}
